# Paths to data and other files 
PANGENOME_MATRIX_CSV = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/pangenome_matrix.csv"
PANGENOME_MATRIX_TXT = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/pangenome_matrix.txt"
PHYLOGROUPS_DATA = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/accessionID_phylogroup2.csv"
TEN_K_DATASET = "/Users/anastasiiashcherbakova/Desktop/diss_track/F4_complete_presence_absence.csv"
TEN_K_DATASET_PHYLOGROUPS = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/accessionID_phylogroup_BD.csv"
TEN_K_DATASET_METADATA = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/metadata_BD.csv"
PAPER_ESSENTIAL_GENES = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/essential_genes.csv"
UNIQUE_GENE_NAMES = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/unique_gene_names.npy"
MINIMIZED_GENOME = "/Users/anastasiiashcherbakova/git_projects/masters_project/data/minimized_genome.fasta"
WILD_TYPE_SEQUENCE = "/Users/anastasiiashcherbakova/Downloads/sequence.gb"